nuxt-community/axios-module

README.md, lib/index.js, lib/plugin.template.js
Otherwise there is the possibility that they are conflicting with each other.
Also added a option, where you can disable the errorHandler at all (for example if you want to work with the responseInterceptor)
=> Override the default error handler when custom error handler is defined

lib/plugin.template.js
Fix for #116: if `currentRequests === 0` then the $loading is always set to 100
=> Fix onProgress

index.d.ts
This will fixes #161.
Before of this commit, Type Definitions define $methods (i.e: $post, $get) returns AxiosPromise<T> (which is Promise<AxiosResponse<T>>), But actually in code it returns data(T), not AxiosResponse.
So I make changes AxiosPromise to Promise, Which just resolved as data(T).
=> Replace AxiosPromise to Promise

lib/plugin.template.js
Resolves https://github.com/nuxt-community/axios-module/issues/170
=> fix(defaults): set proper Accept-Encoding for server side

lib/module.js
From a suggestion from @manniL on the nuxt community discord. I added `cf-ray` and `cf-connecting-ip` to default proxy ignored header.
This solution fixed my own problem with cloudflare proxy and this is also the solution for this issue (#20)
=> feat: add proxyHeadersIgnore in default options

docs/helpers.md
unless i'm crazy, this isn't the right property using the example this is what i see being returned with the latest version of nuxt.
=> wrong property error.code

types/index.d.ts, types/vuex.d.ts
Hey 👋 
When [calling the inject method](https://github.com/nuxt-community/axios-module/blob/dev/lib/plugin.js#L201) we [add to the Vuex Store](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/index.js#L139) the `$axios` key.
Therefore, we need to add its typing.
=> fix(types): correct Vuex Store instance

lib/module.js
check: https://nuxtjs.org/api/configuration-server#basic-example-code-nuxt-config-js-code-
=> feat: use `server` of nuxt.config.js to set default baseURL

lib/module.js
detect if nuxt `server.https` is set, assume that https is being used, preventing CORS errors and streamlining configuration
=> feat: https detection

docs/options.md
some questions:
1 with https, what happens if I use the proxy option ?
2 I can define baseURL this way
{
modules: [
'@nuxtjs/axios'
],
axios: {
baseURL: https://whatever.site/api/
},
}
?
3 Can I define baseURL this way
{
modules: [
'@nuxtjs/axios'
],
env: {
API_URL: https://whatever.site/api/
},
}
4. Can I define baseURL this way
.env file, with dotenv enabled:
...
...
API_URL=https://whatever.site/api/
...
...
?
5
"Note: /api/ will be added to all requests to the API end point. If you need to remove it use pathRewrite": here with "to the API end point" you mean the axios url?
=> docs: improve options

lib/plugin.js
=> fix(progress): handle canceled requests

lib/module.js
=> fix(headers): don't proxy `content-md5` and `content-type`

docs/usage.md, lib/plugin.js
Providing a solution for https://github.com/nuxt-community/axios-module/issues/271 by adding CancelToken and isCancel to the exported axios instance.
Reference: https://github.com/axios/axios/issues/1330#issuecomment-378961682
=> feat: add `CancelToken` and `isCancel` to axios instance

docs/migration.md
The link to the section "Extending Axios" was wrong
=> docs: update migration.md

docs/extend.md, lib/plugin.js, test/axios.test.js, test/fixture/pages/ssr.vue
**This PR resolves #286.** 
I added new method for create copy of $axios instance based on default settings.
After that the copy is independent and may get new options so we can extend it. 
Right now we can't use nuxt/axios in our module, because we won't override axios instance created by user. 
**How it works ?**
$axios.create method returns new Axios instance, you can pass additional options to merge.
```js
const newInstance = this.$axios.create({
headers: {
common: {
Accept: 'text/plain, */*'
}
}
})
```
After that you can use methods from this module, without override base $axios instance. 
```js
newInstance.setBaseURL('https://yourapi.com')
```
I also extended `test/fixture/pages/ssr.vue` to present how the new instance behaves. 
@pi0 Have a look at it please.
=> feat: allow creating new instances

types/index.d.ts
The error is: TS2339: Property 'CancelToken' does not exist on type 'NuxtAxiosInstance'.
https://axios.nuxtjs.org/usage#cancel-token
`const { CancelToken } = this.$axios`
=> fix(types): extend from `AxiosStatic`

lib/module.js, test/axios.test.js
HTTPS on localhost is not possible because of this change.
https://github.com/nuxt-community/axios-module/pull/93
There is no justification as to why this change has been made.
To me it feels like a developer issue and what should have been done is something along the lines of this in the config.
```https: process.env.NODE_ENV === 'development',```
As it stands at the moments the https setting is redundant in localhost and the limitation is not well documented
https://cmty.app/nuxt/axios-module/issues/c346
=> fix(module): always set protocol to `https` when `https: true` is set

lib/plugin.js
This fixes the issue that
```js
const o = {
a: undefined
}
console.log(`${o.a}`)
```
will log `'undefined'`
=> fix(plugin): don't convert falsy urls to string

docs/setup.md
Update TypeScript section in document.
- Change from `Typescript` to `TypeScript` for correct letters and fit to other document (like [here](https://typescript.nuxtjs.org/)).
- Change from `@nuxt/vue-app` to `@nuxt/types` for the latest nuxt.
=> docs(setup): update typescript section

lib/plugin.js
**Problem:**
The `globalName` equals `nuxt` if we didn't set it in `nuxt.config.js`, when you use `window[globalName]` which means `window['nuxt']` to get global `$nuxt`, will return `undefined`, you need use `window['$nuxt']` to get it.
**Solution:**
To get global `$nuxt`, you need use
```javascript
window[`$${globalName}`]
```
So we can define the variable `globalName` with a `$` prefix to make it right.
See source code below to get more info:
https://github.com/nuxt/nuxt.js/blob/85383688371f5ba7b079e1d829a1ada91bc11eaf/packages/config/src/config/_common.js#L16-L23
=> fix(plugin): add missing $ prefix to globalName

types/index.d.ts
Hi, 
With this PR, the axios configuration will be autocompleted in nuxt.config.js for those who use typescript-runtime.
Thanks for your work,
Mathieu.
=> feat(types): add typings to axios config in `nuxt.config`

docs/extend.md
In this case, `redirect` is unnecessary.
=> docs: update extend.md

lib/plugin.js, test/fixture/api.js, test/fixture/pages/cancelToken.vue
At the moment if there is a long running request that should be cancelled (like a video upload or something) the loading bar stays. 
This pr is for decrementing the request cound and hiding the progress bar if last request.
=> fix(plugin): hide progress bar on cancelled requests

types/index.d.ts
As documented in https://axios.nuxtjs.org/options.html#progress, Nuxt Axios
supports passing "progress" boolean through request options.
=> types: extend `Axios.AxiosRequestConfig` with `progress` option

docs/content/en/index.md
=> docs: fix typo

lib/plugin.js
if Content-Length field is missing in response header, the value of e.total is 0, which will cause $loading().set(Infinity)
=> fix $loading().set(Infinity) issue

docs/content/en/helpers.md
In response to https://github.com/nuxt-community/axios-module/issues/241#issuecomment-742822630, this PR aims to document how to globally capture Axios errors.
Looking forward to your feedback.
=> docs: explain global error handling in interceptors

docs/content/en/options.md
Changed `...to make requests server side requests` to `...to make server side requests`.
=> docs(options): remove the duplicated word

docs/content/en/options.md, lib/module.js
As mentioned in #456, some reverse proxies get confused when they get an `x-forwarded-host` and cause loops or incorrectly rewriting the `host` header. I assume the proxying of this header might also cause issues with CloudFlare.
After adding this header to the ignored list my problem was fixed and I have tested the new defaults with CloudFlare reverse proxy and it's working fine.
Note: I've also updated docs to reflect new defaults and explain the purpose of that new default, and removed the note about disabling header proxying altogether when using CloudFlare since this is no longer needed thanks to this commit and previous ones that added the `cf-ray` and `cf-connecting-ip` headers to that same ignore list.
=> fix: add `x-forwarded-host` to `proxyHeaderIgnore` defaults

package.json, yarn.lock
See related issue: https://github.com/axios/axios/pull/3410
It's a security fix which for unknown reason renovate didn't pick it up.
Thanks!
=> chore(deps): update dependency axios to ^0.21.1

types/index.d.ts
Add missing type for `create()` function inside `NuxtAxiosInstance`
resolves #420
=> fix(types): add missing type for `create()`

types/index.d.ts
Update return types of interceptor functions to match axios interceptor and module logic.  
The interceptor implementation provide possibility to return config.
```js
// https://github.com/nuxt-community/axios-module/blob/master/lib/plugin.js#L24
onRequest(fn) {
this.interceptors.request.use(config => fn(config) || config)
},
```
Also Axios interceptors can support async callbacks. And reject handlers can return any type not just `AxiosError`
```ts
// https://github.com/axios/axios/blob/master/index.d.ts#L125
export interface AxiosInterceptorManager<V> {
use(onFulfilled?: (value: V) => V | Promise<V>, onRejected?: (error: any) => any): number;
eject(id: number): void;
}
export interface AxiosInstance {
interceptors: {
request: AxiosInterceptorManager<AxiosRequestConfig>;
response: …
```
=> fix(types): update interceptors type

docs/content/en/options.md
There were some incorrect/strange choices of wording, previously. I feel this is clearer and more to the point.
=> docs(options): update grammar
